### ISSUE TITLE
trafgen: allow for disabling MTU checks inside trafgen

### ISSUE THREAD

**Issue by borkmann** [netsniff-ng/netsniff-ng#103]
Add a command line option that allows to disable internal MTU checks for trafgen. Thus, we would let the kernel do the job instead.

**Comment by vkochan** [comment]
I assume it is implemented by Daniel in the latest commit for trafgen:
f91b1752029fffce868e3331a23c1c8ee741b372

**Comment by borkmann** [comment]
Yep, thanks (forgot that there was even a ticket on that one)!
