### ISSUE TITLE
incorrect timestamps in pcap's?

### ISSUE THREAD

**Issue by mredan** [netsniff-ng/netsniff-ng#129]
when using netsniff-ng 0.5.8 like this: 
netsniff-ng --in eth1 -H --ring-size 1GiB --out /pcaps -J --interval 500MiB --silent --verbose -b 0 -P dump

I seem to be getting bad timestamps on packets. The file names seem to have proper values, but the packets themselves appear to be roughly 160 seconds in the future.

as an example (packets are coming in at about 200mbit/sec on this interface at this time):
tcpdump -tt -nn -c 1 -r dump-1406168980.pcap
reading from file dump-1406168980.pcap, link-type EN10MB (Ethernet)
1406169137.537012 IP 5.5.5.5.46909 > 4.4.4.4.80: Flags [.], seq 1286243091:1286248931, ack 258445073, win 148, length 5840

The machine is NTP sync'd, and the hwclock is correct.

If I use tcpdump to write pcap files, the timestamps are accurate.

if I use netsniff-ng to grab packets from the loopback interface, the timestamps are accurate.

through some testing, it seems that if I disable hardware timestamping in netsniff-ng.c by commenting out these lines:
ret = set_sockopt_hwtimestamp(sock, ctx->device_in);
if (ret == 0 && ctx->verbose)
    printf("HW timestamping enabled\n");

then the timestamps in pcap's become accurate. 

the configure script detects that hw timestamping can be enabled.

I tried just disabling it in the configure script, but the above lines cause a linking error, hence why I commented it out.

I looked around for a way to disable hardware timestamping with ethtool..but could not see a way.

some details about this machine:
Ubuntu 12.0.4
kernel: 3.8.0-39-generic #58~precise1-Ubuntu SMP
NIC Intel I350
Driver igb version: 4.1.2-k

**Comment by tklauser** [comment]
Closing due to age. Feel free to reopen in case this is still an issue.
