### ISSUE TITLE
Unable to build on Debian Beaglebone

### ISSUE THREAD

**Issue by jonnteolsson** [netsniff-ng/netsniff-ng#133]
Hi,

I am trying to build netsniff-ng on a Beaglebone black running Debian, but I am getting this error:

debian@beaglebone:~/netsniff-ng$ uname -a
Linux beaglebone 3.8.13-bone50 #1 SMP Tue May 13 13:24:52 UTC 2014 armv7l GNU/Linux

debian@beaglebone:~/netsniff-ng$ make
Building netsniff-ng toolkit (0.5.9-rc4+) for arm-linux-gnueabihf:
Building netsniff-ng:
  CC    dissector.c
Assembler messages:
Error: unknown architecture `native'

Error: unrecognized option -march=native
cc1: error: bad value (native) for -march switch
cc1: error: bad value (native) for -mtune switch
make: *** [netsniff-ng/dissector.o] Error 1
debian@beaglebone:~/netsniff-ng$

Any idea?

Thanks!

**Comment by tklauser** [comment]
This should be solved by commit cc3fe524c2daa8c136e6484540130da7252a8f1b where we remove the x86 specific compiler flags alltogether, thus closing this issue. Feel free to reopen if this didn't fix it for you. Thanks!
