### ISSUE TITLE
Error on trafgen

### ISSUE THREAD

**Issue by user1020** [netsniff-ng/netsniff-ng#137]
I am using the latest from this repo as of Dec 
```
https://github.com/netsniff-ng/netsniff-ng.git
```
However, the trafgen gave me error:

```
/root/pkgs/netsniff-ng/trafgen#./trafgen -e | ./trafgen -i - -o em1 --cpp -n 1
Syntax error at line8, at char 't'! syntax error, unexpected number!
```
Any ideas?

My system is Fedora release 20, kernel 3.11.10-301.fc20.x86_64

Thanks.

**Comment by vkochan** [comment]
stddef.h should be in /etc/netsniff-ng which should be copied by 'make install' from the src folder of
netsniff-ng.

Seems this error might happen if to run fresh compiled netsniff-ng which is not installed
in the OS.

May be there might be some simple work around for this special case like to use trafgen_stddef.h
from the current dir.

**Comment by vkochan** [comment]
Seems like it might be closed.

**Comment by tklauser** [comment]
Closing, as this can be solved by installing trafgen_stddef.h to /etc/netsniff-ng or by specifiying an absolute path as pointed out by @pavel-odintsov and @vkochan.

Feel free to reopen if you still see this as an issue.
