### ISSUE TITLE
Reserved names

### ISSUE THREAD

**Issue by signoredeltempo** [netsniff-ng/netsniff-ng#139]
The code has multiple undefined behavior points because of declaration and/or definition with reserved names, namely two underscores followed by a lower case letter (e.g. "__name") or one underscore and a capitalized letter (e.g. "_Name").

**Comment by borkmann** [comment]
Could you elaborate on the concrete function signature or variable? Thanks!

**Comment by signoredeltempo** [comment]
Yeah, sure. In pcap_mm.c, for example, you define `__pcap_mmap_write_need_remap(int fd)`, which is not allowed by such rules. See [this](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier) for more info.

**Comment by tklauser** [comment]
Does this cause any trouble (i.e. build failures) currently besides "breaking" the standard?

If not, I'd say this is not really critical. Changing these identifiers just for standard compatibility's sake is not worth it IMO.

**Comment by signoredeltempo** [comment]
Would it be ok for you if GCC defined `builtin_expect` in *your* name space instead of its (the one of the implementation)? 
Anyways, the behavior is simply undefined. Most of the times, it will compile just fine because it's unlike anything beginning with `pcap` being defined; but it could just suddenly stop or even worse.

It's a pretty simple substitution, however, which you might or might not want to fix (it's no different from dereferencing `NULL`, actually). What you'd better consider, IMHO, is to no longer break it and so establish a more legal naming convention.
