### ISSUE TITLE
netsniff-ng: If using rotated intervals, flush to disk on SIGHUP

### ISSUE THREAD

**Issue by dcode** [netsniff-ng/netsniff-ng#140]
If a user needs to analyze PCAP that's currently in the ring buffer, he may have to wait and poll on a given file until the PCAP is available. Alternatively, he could restart netsniff-ng, but this causes a loss in collection. Ideally, a SIGHUP would induce the file to rotate prematurely in the interval. The user can then run tshark or mergecap on the file and access the desired PCAP.

**Comment by tklauser** [comment]
Thanks for your suggestion! I implemented something along these lines in 46289df6bc8f573bc01be4fb4aa93343ecc6d50a

Could you please check whether this fits your needs?

**Comment by dcode** [comment]
Beautiful! Thanks!

**Comment by tklauser** [comment]
In that case I consider this fixed :) Feel free to reopen (or open a new issue) if something doesn't work as expected.
