### ISSUE TITLE
curvetun is hyper sensitive to time and clock drifting, needs a reliable NTP source?

### ISSUE THREAD

**Issue by zoobab** [netsniff-ng/netsniff-ng#141]
Hi,

I am raising this issue as I have had the impression that curvetun is super sensitive to clock differences.

My tunnel was not working, and when I resynced the machine with ntpdate to an NTP server, it worked again.

Could you mention somewhere in bug fat warning that you need a decent NTP clock sync to make it work properly?

**Comment by tklauser** [comment]
This is mentioned in the manpage:
https://github.com/netsniff-ng/netsniff-ng/blob/e843d29eec50dfcad948859b545eaf529731d28e/curvetun.8#L219
and we expect users to consult the manpage (at least in case of problems :wink:), so I consider this fixed.
