### ISSUE TITLE
support shell vars in trafgen

### ISSUE THREAD

**Issue by borkmann** [netsniff-ng/netsniff-ng#143]
Quote from mailing list:

" Is it possible to use shell variables in the configuration file? The use case I have is a script that sets variables such as IP address ( $SrcIP_Byte1 , $SrcIP_Byte2 , $SrcIP_Byte3 , $SrcIP_Byte4 ) then trafgen is  called using a standard configuration file, but the variables $SrcIP_Byte1 etc are referenced from within the config file itself The alternative is that the shell script use 'sed' or other means of manipulating the config file, but variables are so much easier. "

So we would need to add a textual replacement before parsing.

**Comment by vkochan** [comment]
Added possibility to pass C preprocessor's macro/define via newer -D option (in combination with -p,--cpp option) in trafgen by commit:

126e0038a73b38fac7b3e03173b2d791734cc497

and this allows to use C preprocessor #ifdef with these defines in trafgen script.

**Comment by tklauser** [comment]
Thanks Vadim. I'd say we can thus close this now.
