### ISSUE TITLE
Header Only Capture

### ISSUE THREAD

**Issue by aconite33** [netsniff-ng/netsniff-ng#149]
Will netsniff ever bring back the option to only capture header information of network traffic? It was very useful on a project I am working on.

It was present in version 0.5.6 but removed after 0.5.7. Any reason why this was done and if it will come back as an option?

**Comment by borkmann** [comment]
You can do this already today. Run netsniff-ng with a BPF program that detects and cuts off headers.

Have a look here:

https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/net/core/filter.c?id=3e5289d5e3f98b7b5b8cac32e9e5a7004c067436

**Comment by aconite33** [comment]
Alright, I see how you can create a filter using bpfc. However using the example listed for only capturing the packet header keeps giving an error for syntax:
#> cat fubar.bpfc
ld poff
ret a
#> bpfc fubar.bpfc > fubar.bpf
Syntax error at line 1: poff! syntax error, unexpected label, expecting '[' or 'M' or '#'!

**Comment by borkmann** [comment]
Works for me:
```
# cat foo
ld poff
ret a
# bpfc foo > bar
# netsniff-ng -i any -f bar
```
Have you tried a more recent version?

**Comment by tklauser** [comment]
Considering this fixed as per the following comment edit by the original reporter:

> ****Disregard. Version used in Ubuntu for netsniff-ng is outdated. Pulled the latest from github, worked perfectly.
