### ISSUE TITLE
Failed curvetun compilation with shared nacl

### ISSUE THREAD

**Issue by yarda** [netsniff-ng/netsniff-ng#152]
This may be because our shared nacl in Fedora is non-standard (maybe old), but I had to add '-lstdc++' to the link libraries in curvetun/Makefile. Then it compiled/linked without problem.

**Comment by yarda** [comment]
Or maybe it's also due to our ImplicitDSOLinking (https://fedoraproject.org/wiki/Features/ChangeInImplicitDSOLinking). I can do pull request, but this is trivial.

**Comment by tklauser** [comment]
Hi Jaroslav

Thanks for the report.

I'm not entirely sure how this would be related to libstdc++, AFAIK nacl is (and has always been) a pure C library. In any case, I'd like to omit any additional build time dependencies (especially on C++ libraries) if somehow possible. I'll have a closer look at it...

FWIW, you might want to switch to libsodium anyhow, which is a bit more convenient with regards to packaging, porting, cross-compiling etc. See f4edc7180e472779682df2e5a115c9713755ff9b (also the Debian package was switched to use libsodium)

**Comment by yarda** [comment]
We have compiled nacl in Fedora as shared library. Not sure why libstdc++ dep is there, maybe we have something wrong. I will also take closer look.

Thanks for the info, I think I can switch to libsodium in Fedora.

**Comment by yarda** [comment]
Switched to libsodium in Fedora Rawhide (netsniff-ng-0.6.0-2.fc24).

**Comment by tklauser** [comment]
Closing this now as building with libsodium seems to have solved the issue. Please feel free to reopen the issue if you think this is still a problem. Thanks!
