### ISSUE TITLE
mausezahn -F (hex payload) forces first byte to 0

### ISSUE THREAD

**Issue by patrickdepinguin** [netsniff-ng/netsniff-ng#153]
Running mausezahn as follows:

    mausezahn eth1 -F /tmp/payload

causes the first byte of the payload to be transmitted as 0, regardless of the actual byte in /tmp/payload.
This was reported before at [1] but apparently with no reply. The problem is still present on mausezahn 0.6.0.
I have verified that the patch proposed by [1] fixes the problem.

For reference, the patch applied is:

    diff --git a/staging/layer1.c b/staging/layer1.c
    --- a/staging/layer1.c
    +++ b/staging/layer1.c
    @@ -58,7 +58,8 @@ int send_eth(void)
          j=0;
        char 
          err_buf[LIBNET_ERRBUF_SIZE],
    -     message[MAX_PAYLOAD_SIZE*3];
    +     message[MAX_PAYLOAD_SIZE*3],
    +     argval[MAX_PAYLOAD_SIZE*2];
          
        u_int8_t       bytestring[MAX_PAYLOAD_SIZE];
        libnet_ptag_t  t;
    @@ -100,7 +101,10 @@ int send_eth(void)
        // Create a temporal, local bytestring:
        //
        for (i=0; i<MAX_PAYLOAD_SIZE; i++) bytestring[i]=0x00;
    -   bytestring_s = str2hex (tx.arg_string, bytestring, MAX_PAYLOAD_SIZE);
    +   if ( (getarg(tx.arg_string,"payload", argval)==1) || (getarg(tx.arg_string,"p", argval)==1))
    +     {
    +	bytestring_s = str2hex (argval, bytestring, MAX_PAYLOAD_SIZE);
    +     }
        
        // Set the flags to shorten subsequent decisions:
        src = strlen(tx.eth_src_txt);

Credits for this patch go to Thomas Fleischmann.

[1] http://permalink.gmane.org/gmane.linux.network.netsniff-ng/600

**Comment by tklauser** [comment]
Sorry, I missed the message/patch on the mailing list back then.

Thanks a lot for reminding me, patch now applied.
