### ISSUE TITLE
Send incorrect interface when use Mausezahn

### ISSUE THREAD

**Issue by FredLien** [netsniff-ng/netsniff-ng#159]
Hi,

The issue is the incorrect interface to which packet send when using Mausezahn packet generator.
The command is like "mausezahn ens1f1 -b bcast -a rand -t udp"

Because v197 systemd/udev will assign the interface naming not like traditional way (eth0, eth1...). The interface named "ens1f0" cannot be given, it will use other candidate device. The packet will be send from other candidate interface.

The following can solve but please check if it's suitable to the solution.
Thanks. :)

Regards,
FredLien

------
diff --git a/staging/mausezahn.c b/staging/mausezahn.c
index 70f1e72..4e294c3 100644
--- a/staging/mausezahn.c
+++ b/staging/mausezahn.c
@@ -599,6 +599,7 @@ int getopts (int argc, char *argv[])
         case 1: // arg_string OR device given => find out!
                if ( (strncmp(argv[optind],"eth",3)==0)
                     || (strncmp(argv[optind],"ath",3)==0)
+                    || (strncmp(argv[optind],"ens",3)==0)
+                    || (strncmp(argv[optind],"eno",3)==0)
                     || ((strncmp(argv[optind],"lo",2)==0)&&(strncmp(argv[optind],"log",3)!=0))
                     || (strncmp(argv[optind],"vmnet",5)==0)
                     || (strncmp(argv[optind],"wifi",4)==0) ) {
------

**Comment by vkochan** [comment]
Hi,

I think that better fix (IMHO) might be to get list of interfaces and match argument over this list.

**Comment by tklauser** [comment]
Yes, I agree with Vadim's proposal. The best solution would be to use __device_ifindex with the given device name and check the return value (valid device if the ifindex >= 0).
