### ISSUE TITLE
GENL_ID_GENERATE removed from netdev

### ISSUE THREAD

**Issue by yarda** [netsniff-ng/netsniff-ng#171]
It seems that GENL_ID_GENERATE was removed from kernel 4.10, which prevents compilation of netsniff-ng.

Discussion about it (at time of filling this it was undecided whether it will be returned back):
https://www.spinics.net/lists/netdev/msg423041.html

The commit introducing the change:
https://git.kernel.org/cgit/linux/kernel/git/bwh/linux-stable.git/commit/?id=a07ea4d9941af5a0c6f0be2a71b51ac9c083c5e5

**Comment by tklauser** [comment]
Thanks for the report! GENL_ID_GENERATE is now removed from netsniff-ng as well with commit 88ec2ad.
