### ISSUE TITLE
Issues compiling netsniff-ng against libmusl

### ISSUE THREAD

**Issue by archey** [netsniff-ng/netsniff-ng#173]
I am currently working on building a package for alpinelinux and I wanted to add netsniff-ng to the repos. However it seems to be having issues compiling against libmusl:

This is building against the latest netsniff-ng v0.6.3 and musl v1.1.15 and gcc v6.2.1

Building netsniff-ng toolkit (0.6.3+) for x86_64-alpine-linux-musl:

https://gist.github.com/archey/5513d3b4319dbd300d480527035b6250

**Comment by tklauser** [comment]
I wasn't able to reproduce this on Alpine Linux 3.52 with netsniff-ng 0.6.3, musl 1.1.15 and gcc 6.2.1.

How do you invoke make? Do you pass any additional configuration variables (e.g. `HARDENING`, `DEBUG`)? What is the output of `./configure`?

**Comment by archey** [comment]
The configure output is basically just ./configure --prefix=/usr

https://gist.github.com/archey/a059c58be2b37e66f5db589b198770bb

The above link is the build log and the last few lines of the config.log

**Comment by archey** [comment]
I was missing some deps like geoip-dev and libnfnetlink-dev, however it still is failing with the same compilation errors. 

After fixing deps the build output looks like:

https://gist.github.com/archey/2a4e0ae248224b30bfd5dfa71a4ea880

**Comment by tklauser** [comment]
This seems to be caused by the Alpine Linux fortify-headers. Once I `apk add fortify-headers`, I can reproduce the problem.

As I'm neither familiar with Alpine Linux nor their fortify headers setup, so for now I can only suggest disabling header fortification by passing `-D_FORTIFY_SOURCE=0` in `CPPFLAGS`.

**Comment by archey** [comment]
They unfortunately dont like the idea of removing the fortify_source line and they wont accept the pr if I add it in. I think it may be difficult to get this added to their repo, due to that issue.

**Comment by tklauser** [comment]
I think I finally found the issue. In built_in.h we have the following:
```
#undef memset
#undef memcpy

#define memset         fmemset
#define memcpy         fmemcpy
```
This causes the corresponding definitions in the fortified `string.h` to fail.

I think, these should be removed anyhow and we should only use `fmemset` specifically where we want the compiler builtin to be used. I'll push a fix shortly...

**Comment by tklauser** [comment]
The netsniff-ng toolkit should now build fine on Alpine Linux with fortify-headers in place. Please reopen if you still see problems.

**Comment by archey** [comment]
@tklauser its closer to building after applying the patch, it looks like trafgen is failing now.

https://gist.github.com/archey/67f3f40c76c57751c4d3bc46a65e5f55

**Comment by archey** [comment]
This tiny patch fixes the issue with missing ino_t:

https://gist.github.com/archey/302f540c6f37284e4002fbd5c0b0ce7f

However it looks like trafgen is calling libintl.h which appears to be a header file specific to glibc. 

https://gist.github.com/archey/6dd24691783d6a3d6d6cf3fce79e6d7d
