### ISSUE TITLE
Issues compiling trafgen with musl

### ISSUE THREAD

**Issue by archey** [netsniff-ng/netsniff-ng#174]
I am having a few issues compiling trafgen against musl. I was able to patch one issue with the small patch here:
build log: https://gist.github.com/archey/67f3f40c76c57751c4d3bc46a65e5f55

This tiny patch fixes the issue with missing ino_t:

https://gist.github.com/archey/302f540c6f37284e4002fbd5c0b0ce7f

However trafgen is now failing due to a redefinition error:

https://gist.github.com/archey/07a79b85d446c2d2532ff46bb5e5c4f0

**Comment by archey** [comment]
I fixed a few issues here and applied a few missing patches and its a lot closer.

build log: https://gist.github.com/archey/6d3cfc1e8888674a97f78b457fa83453

I have applied the following patches

https://github.com/netsniff-ng/netsniff-ng/commit/f232545c215022de5be5e0b37e0c7130962cc5d0

https://github.com/netsniff-ng/netsniff-ng/commit/b25a51fa5915df87f31a0cc0459cd9f05e17f540

https://github.com/netsniff-ng/netsniff-ng/commit/a9f4431e0a205617bb316dbe459ac6188dd8b490

https://github.com/netsniff-ng/netsniff-ng/commit/a5a5a91342ebd83d13b8eff8f85d9c923e08f701

**Comment by tklauser** [comment]
After applying 5ca91a807a81db233e1b4443ea227bb1d0a7868f and b118a01871cfb26c0f537889da2a35c6b2ca7f3d the libintl issues should be gone as well. Care to try?

**Comment by archey** [comment]
Sure I will test it right now, thanks for helping out with this. I know its been alot of changes and fixes to the source code.

**Comment by archey** [comment]
Trafgen is fixed after applying those two patches as well as the patches I listed above. However I am seeing a issue with curvetun as well:

build log: https://gist.github.com/archey/da240d7139ec72fe380547a9955d091d

In doing some research it appears that cookie.c needs 

#define _GNU_SOURCE
#include <stdio.h>

However I looking at the source code for the cookie.c file I see that is already defined at the very top.

**Comment by Shizmob** [comment]
musl doesn't have `fopencookie()`, but it can be reimplemented in terms of usual libc functionality, as the patches here do: http://cgit.openembedded.org/openembedded-core/tree/meta/recipes-extended/libsolv/libsolv?id=378b333fb09d106fb04901f5a4362fc0eb076e82

**Comment by tklauser** [comment]
`curvetun` is the only tool using `fopencookie(3)` and carrying a patch just for that is not worth the effort IMO. Instead, we now just disable building `curvetun` in case `fopencookie()` is not available (e.g. when compiling against musl), see e843d29.
