### ISSUE TITLE
trafgen: child processes panic() during resource deallocation

### ISSUE THREAD

**Issue by EduardoMiravalls** [netsniff-ng/netsniff-ng#175]
Dear trafgen maintainer(s):

I'm experiencing an issue due to a "race condition"-like phenomena during resource deallocation.

I'm trying to stress test a device sending 1gbps traffic of 64byte-length packets using trafgen to generate the load. However, I'm experiencing this issue with any packet size up to 1514. The bug happens every time trafgen is launched with more than 1 CPU.

At the end of the stress test, each child process panic()s during resource deallocation with an error "Cannot destroy the TX_RING: device or resource busy!", and eventually the main process die()s without printing the final statistics.

After compiling trafgen in debug mode, I've narrowed it down to the call "destroy_tx_ring()". The panic() happens after "pull_and_flush_tx_ring_wait(sock)" returns -1, which in my system happens every time. Finally, the main process is calling die() in trafgen.c:1385 after all its children finished with EXIT_FAILURE.

My system is based on an old Intel(R) Core(TM) i7 CPU 860 @ 2.80GHz running on an Acer H57M01 board, and my OS is Ubuntu 14.04 MATE with kernel "4.4.0-78-generic #99~14.04.2-Ubuntu SMP Thu Apr 27 18:49:46 UTC 2017 x86_64". 

I launch my tests with this command:

    sudo trafgen --cpp --in "udp_22.trafgen" --out eth2 --num  19531250

the number of packets is computed so the test lasts 10 seconds.

This is my configuration file (based off one of your examples):

    $ cat udp_22.trafgen 
    /* This file need to be run with --cpp for c-preprocessor call.

    Command example:
     trafgen --cpp --dev dummy0 --conf udp_example01.trafgen \
      --cpu 2 --verbose \
      --ring-size 500KiB

    original source: https://github.com/netoptimizer/network-testing/blob/master/trafgen/udp_example01.trafgen
    */
    #define ETH_P_IP    0x0800

    {
      /* --- Ethernet Header --- */
      /* NEED ADJUST */
      0x00, 0x1e, 0x06, 0x33, 0xe7, 0xb4,  # MAC Destination
      0x00, 0x10, 0x18, 0xc4, 0x7e, 0x1a,  # MAC Source
      const16(ETH_P_IP),

      /* --- IPv4 Header --- */
      0b01000101, 0,  /* IPv4 Version, IHL, TOS */
      const16(50),    /* IPv4 Total Len (UDP len + IP hdr 20 bytes)*/
      const16(2),     /* IPv4 Ident */
      0b01000000, 0,  /* IPv4 Flags, Frag Off */
      64,             /* IPv4 TTL */
      17,             /* Proto UDP */
      csumip(14, 33), /* IPv4 Checksum (IP header from, to) */

      /* --- UDP Header --- */
      /* NEED ADJUST */
      192, 168, 1, 66,  /* Source IP */
      192, 168, 1, 33,  /* Dest IP */

      const16(6666), /* UDP Source Port e.g. drnd(2)*/
      const16(6666), /* UDP Dest Port */
      const16(30),   /* UDP length (UDP hdr 8 bytes + payload size */

      /* UDP checksum can be dyn calc via csumudp(offset IP, offset TCP)
       * which is csumudp(14, 34), but for UDP its allowed to be zero
       */
      const16(0),

      /*** Payload ***/
      drnd(22),
    }

However, I've found a workaround, which lead me to believe this is some sort of race-condition:

    diff --git a/trafgen.c b/trafgen.c
    index b25760f..40840c8 100644
    --- a/trafgen.c
    +++ b/trafgen.c
    @@ -816,6 +816,7 @@ static void xmit_fastpath_or_die(struct ctx *ctx, unsigned int cpu, unsigned lon
            timersub(&end, &start, &diff);
     
            pull_and_flush_tx_ring_wait(sock); /* this is returning -1! */
    +       sleep(1); /* race condition? bug goes away with this! */
            destroy_tx_ring(sock, &tx_ring);
     
            stats[cpu].tx_packets = tx_packets;

However this is not a proper fix, since I am not addressing the source of the error, just waiting for it to go away ;)

Would you mind to look for what is causing my children to panic()?

Thank you.

**Comment by vkochan** [comment]
Looks like it is needed to use some conditional wait mechanism with shared mutex between trafgen
processes. Tobias what do you think ?

**Comment by tklauser** [comment]
@vkochan I don't think a mutex will be necessary. Just let the kernel signal each process when to continue. How about something like the following?

```
diff --git a/trafgen.c b/trafgen.c
index b25760ff01ef..2ec487a616d8 100644
--- a/trafgen.c
+++ b/trafgen.c
@@ -815,7 +815,8 @@ static void xmit_fastpath_or_die(struct ctx *ctx, unsigned int cpu, unsigned lon
        bug_on(gettimeofday(&end, NULL));
        timersub(&end, &start, &diff);
 
-       pull_and_flush_tx_ring_wait(sock);
+       while (pull_and_flush_tx_ring_wait(sock) < 0 && errno == ENOBUFS)
+               ;
        destroy_tx_ring(sock, &tx_ring);
 
        stats[cpu].tx_packets = tx_packets;
```

**Comment by EduardoMiravalls** [comment]
That seems to work in my system.

Out of curiosity, why don't you add a small sleep in that loop? (for example, usleep(500);   or a sleep(0) as it is used somewhere else in that file)

I mean, why are they now able to release their tx_rings just by letting them try continuously to flush them? Since that errno seems to indicate that there were not enough resources to finish the operation, waiting a bit between each try may save hundreds of calls (not sure if that makes any difference, just a curiosity).

**Comment by tklauser** [comment]
@EduardoMiravalls Yes, adding a {u,}sleep in the loop as well as a timeout certainly make sense. Just wanted to verify the general approach works for you. Will push a polished version soonish. Thanks!
