### ISSUE TITLE
Compilation error with gcc-7

### ISSUE THREAD

**Issue by yarda** [netsniff-ng/netsniff-ng#176]
Compilation in Fedora Rawhide fails:
https://kojipkgs.fedoraproject.org//work/tasks/8807/20308807/build.log

It's missing stdint.h include.

**Comment by yarda** [comment]
Fixed by https://github.com/netsniff-ng/netsniff-ng/pull/177

**Comment by tklauser** [comment]
Fixed by 551aa0ee996132e443b5d12cbb6f114ac9aabcd3 through #177. Thank you @yarda!
