### ISSUE TITLE
trafgen to pcap leads to segfault

### ISSUE THREAD

**Issue by bodik** [netsniff-ng/netsniff-ng#188]
while trying to come up with some basic test cases for our new python wrapper around trafgen (https://github.com/bodik/ddos-cz2/tree/master/tg) we might hit some weird initialized structure `dev->pcap_ops` during generating pcap files.

pcap is generated just fine and contain proper packet with all fields, but segfault is thrown in dev_pcap_close  while dereferencing  `dev->pcap_ops->prepare_close_pcap` at https://github.com/netsniff-ng/netsniff-ng/blob/abafb7e1679f268fea1f5b0f911cb75fcda44857/trafgen_dev.c#L155

```
INFO: test for UdpRandomPayload /tmp/tg2_test_8235.1520289025.pcap /tmp/tg2_test_8235.1520289025.pcap.displayed
DEBUG generator fields: {'udp_total_length': 251, 'udp_destination_port': 'c16(48449)', 'eth_protocol': '0x800', 'generator': 'UdpRandomPayload', 'dump': False, 'eth_destination_mac': '0x9b,0xf9,0x10,0x39,0x9e,0x90', 'udp_source_port': 'c16(44961)', 'eth_source_mac': '0x66,0xa6,0x75,0x96,0xa0,0x54', 'ip_destination_address': '255,182,135,251', 'dev': '/tmp/tg2_test_8235.1520289025.pcap', 'gap': None, 'ip_ttl': '3', 'rate': None, 'num': '1', 'time': None, 'debug': True, 'length': 243, 'ip_total_length': 271, 'ip_source_address': '215,179,39,54', 'ip_protocol': '17'}
DEBUG ['/root/ddos-cz2/tg/bin/trafgen', '--in', '/tmp/tg2_generator_ElpR0N', '--out', '/tmp/tg2_test_8235.1520289025.pcap', '--cpp', '--num', '1']
DEBUG 1 packets to schedule
   285 bytes in total
Running! Hang up with ^C!
ERROR exit code -11
```

```
Core was generated by `./trafgen --in /tmp/tg2_generator_2TwssP --out /tmp/tg2_test_8447.1520289729.pc'.
Program terminated with signal SIGSEGV, Segmentation fault.
;#0  0x000055f29c2238d8 in dev_pcap_close (dev=0x55f29dbbd070) at trafgen_dev.c:155
155		if (dev->pcap_ops->prepare_close_pcap)
...
(gdb) print *dev
$5 = {fd = 0, name = 0x55f29dbbd0d0 "/tmp/tg2_test_8447.1520289729.pcap", trans = 0x0, ifindex = 0, dev_type = 0, link_type = 0, pcap_magic = 0, is_initialized = false, pcap_mode = PCAP_MODE_RD, mode = DEV_IO_OUT, 
  buf_len = 0, buf = 0x0, pcap_ops = 0x0, ops = 0x55f29c447e20 <dev_pcap_ops>}
```

I'm willing to dig in the problem, but I'd appreciate any pointer where to look ...

**Comment by tklauser** [comment]
@bodik Thanks for your report. Which version of the netsniff-ng toolkit are you using? Does the segfault occur with any type of input file? Care to provide an example file?

In any case, I guess changing the condition at https://github.com/netsniff-ng/netsniff-ng/blob/abafb7e1679f268fea1f5b0f911cb75fcda44857/trafgen_dev.c#L155

to 

```c
if (dev->pcap_ops && dev->pcap_ops->prepare_close_pcap)
```

should fix the segfault. Still, I'd like to understand why it happens.

**Comment by bodik** [comment]
thanks for reply, we'r using builded HEAD from few days ago, but we can run our testsuite on arbitrary version you might ask

```
# git reflog
b90d055 HEAD@{0}: clone: from https://github.com/netsniff-ng/netsniff-ng

# bin/trafgen --version
trafgen 0.6.4+ (Spiral Staircase), Git id: v0.6.4-3-gb90d055
```


We've added few more testcases (https://github.com/bodik/ddos-cz2/blob/master/tg/tests/test_basic.sh) and it seems that crash occurs when trafgen is invoked with `--num`, but it does not crash when trafgen is terminated by externaly signal.


Example config (but virtualy any config we have; with or without commens; with or without using `--cpp`):
```
# cat /tmp/tg2_githubtest
{
/* payload */				0
}
```

#### example run 1
generates 1 packet and segfaults
```
# ./trafgen --in /tmp/tg2_githubtest --out /tmp/tg2_githubtest.pcap --cpp --num 1
     1 packets to schedule
     1 bytes in total
Running! Hang up with ^C!


           1 packets outgoing
           1 bytes outgoing
           0 sec, 39179 usec on CPU0 (1 packets)
Segmentation fault
```



#### example run 2
generates 1 packet and terminates properly
```
# timeout 1 ./trafgen --in /tmp/tg2_githubtest --out /tmp/tg2_githubtest.pcap --cpp --rate 1pps
     1 packets to schedule
     1 bytes in total
Running! Hang up with ^C!


           1 packets outgoing
           1 bytes outgoing
           0 sec, 981298 usec on CPU0 (1 packets)
```


can you reproduce same results with your own builds?

**Comment by tklauser** [comment]
Thanks for the extended information. I can indeed now reproduce the problem. It seems `dev_pcap_close` is called twice (i.e. from multiple threads, because we always fork at least once, even for 1 CPU) and the second invocation causes the segfault. AFICS we need to call `dev_pcap_close` in the parent only.

**Comment by bodik** [comment]
> dev_pcap_close is called twice (i.e. from multiple threads, because we always fork at least once, even for 1 CPU) and the second invocation causes the segfault. AFICS we need to call `dev_pcap_close` in the parent only.

nice to hear, I completely missed the `fork` (even though I saw forks in process list), but according to gdb, the struct is initialized only in child, so there should be some more changes than just `if(pid)` in label: `thread_out` i guess ?

**Comment by tklauser** [comment]
Yes, I think calling `dev_io_close` at `thread_out` is wrong to begin with (and the other clean tasks therein should also only be done in the parent IMO). I'm working on a fix and will submit it once I verified trafgen still works in all use cases.

**Comment by bodik** [comment]
> should also only be done in the parent IMO). I'm working on a fix and will submit it once I verified trafgen still works in all use cases.

I've deleted my previous post because I was wrong about struct init there so I messed up conversation a little bit ;) I'll wait for your fix, just let me know if I could be of any help

**Comment by tklauser** [comment]
@bodik I just pushed the fix and I can no longer reproduce the segfault with it. Feel free to reopen if you still encounter the problem. Thanks a lot for your help!

**Comment by bodik** [comment]
works for me, thank you very much
