### ISSUE TITLE
http://pub.netsniff-ng.org/netsniff-ng/ is not https!

### ISSUE THREAD

**Issue by kartikm** [netsniff-ng/netsniff-ng#196]
As per my Lintian friend from Debian:

I: netsniff-ng source: debian-watch-uses-insecure-uri http://pub.netsniff-ng.org/netsniff-ng/
N:
N:    The watch file uses an unencrypted transport protocol for the URI such
N:    as http:// or ftp://. It is recommended to use a secure transport such
N:    as HTTPS for anonymous read-only access.
N:
N:    Upstream may already provide a HTTPS variant of the URI. If not, please
N:    contact them and ask them to consider adding one.
N:
N:    Severity: wishlist, Certainty: certain
N:
N:    Check: watch-file, Type: source

Please fix this! :)

**Comment by tklauser** [comment]
It seems the debian package was switched to use https://mirror.distanz.ch/netsniff-ng, thus closing this issue.
