### ISSUE TITLE
astraceroute: ICMP and TCP checksum calculation is not carried out

### ISSUE THREAD

**Issue by uno20001** [netsniff-ng/netsniff-ng#200]
I assume it is not intentional that _astraceroute_ does not calculate the ICMP and TCP checksums. As in my case it causes the program not to work (or to work only partially), and I suspect that this problem might be behind issue #198. Until further confirmation I did not want to create a pull request and add checksum calculation, so please confirm if it is intentional or not. (I tested it - although not very thoroughly - and it seems to work properly if checksum calculation is in place.)

Thank you in advance.

**Comment by tklauser** [comment]
I think this might indeed be an oversight on our side. Feel free to send a PR.
