### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by kartikm** [netsniff-ng/netsniff-ng#227]
Hi,

Is it possible to have new minor release of netsniff-ng? Package has been removed from testing due to gcc10 build failure issue.

Release would be great, else I would use patched version soon to fix.

Thanks!

**Comment by tklauser** [comment]
Thanks for the reminder @kartikm. Will tag a new release later today.

**Comment by tklauser** [comment]
Released netsniff-ng v0.6.8: https://github.com/netsniff-ng/netsniff-ng/releases/tag/v0.6.8

**Comment by kartikm** [comment]
Thanks. Uploaded 0.6.8 to Debian unstable.
